# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

import mlx.core as mx

if TYPE_CHECKING:
    from vllm_metal.attention.context import PagedAttentionContext


@runtime_checkable
class PagedAttentionRuntime(Protocol):
    def initialize(self, num_blocks: int) -> None: ...
    def patch_model(self, model: Any) -> int: ...
    def warm_up(self) -> None: ...
    def num_blocks(self) -> int: ...
    def kv_scheduler_group_indices(self) -> tuple[int, ...]: ...
    def kv_group_block_sizes(self) -> tuple[int, ...]: ...
    def state_scheduler_group_indices(self) -> tuple[int, ...]: ...
    def copy_blocks(self, block_copies: Sequence[tuple[int, int]]) -> None: ...
    def needs_step_context(self) -> bool: ...
    def populate_step_context(
        self,
        *,
        req_ids: list[str],
        ctx: PagedAttentionContext,
        state_block_ids: list[list[list[int]]] | None = None,
        step_positions: list[tuple[int, int]] | None = None,
    ) -> None: ...
    def extend_forward_eval_outputs(self, outputs: list[mx.array]) -> None: ...
    def release_requests(self, req_ids: set[str]) -> None: ...
    def materialize_pending_state(self) -> None: ...
