# SPDX-License-Identifier: Apache-2.0
"""Gemma4 MTP checkpoint contract constants."""

GEMMA4_MTP_DEFAULT_VOCAB_SIZE = 262144
GEMMA4_MTP_DEFAULT_NUM_CENTROIDS = 2048
GEMMA4_MTP_DEFAULT_CENTROID_TOP_K = 32
GEMMA4_MTP_N_PREDICT = 1
GEMMA4_MTP_PREPROJECTION_INPUTS = 2
