name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [macos-15]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Lint
      run: |
        scripts/lint.sh

  test:
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.3.app/Contents/Developer
      MACOSX_DEPLOYMENT_TARGET: "15.0"
    permissions:
      contents: read
    strategy:
      matrix:
        os: [macos-15]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Test
      run: |
        scripts/test.sh
